---
title: 從網路下載圖片
hero_image: images/banner.png
description: 從網上獲取圖片的描述
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: 創作者，設計-0，寫程式-1，物理運算-0，製造-0，社群-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: 尋找與下載圖片
