---
title: 인터넷에서 사진 얻기
hero_image: images/banner.png
description: 웹에서 일반 가져 오기 그림 설명
theme: 빨강색 #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: 작성자, 디자인 -0, 프로그래밍 -0, phys-comp-0, 제조 -0, 커뮤니티 -0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: 사진 찾기 및 다운로드
