---
title: Obtenir des images sur Internet
hero_image: images/banner.png
description: description générique de obtenir-à partir-du net
theme: rouge
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Trouver et télécharger une image
